version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/usr/src/app/data
    
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - server